config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  
  devise_for :users
  
  resources :orders, only: [:create]

  constraints UserConstraint.new do
    get  'dashboard' => 'dashboard#index'
    match "/split" => Split::Dashboard, :anchor => false, :via => [:get, :post, :delete]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  # visitable
  #   add_column :orders, :visit_id, :integer
  # 
  validates :email, presence: true, uniqueness: true #,
                    # format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_presence_of :short_name, :message
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # after_filter :track_action

protected

  def track_action
    ahoy.track "Processed #{controller_name}##{action_name}", request.filtered_parameters
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'

  def index
    @orders_today = Order.where("created_at::date = ?", Date.today - 1).count
    @orders_total = Order.count
    @not_admin_events = Ahoy::Event.where(user_id:nil) # for table
    @not_admin_land_views = @not_admin_events.where(name: "Processed landing#index")
    @land_views_today = @not_admin_land_views.where("time::date = ?", Date.today - 1).count
    @land_views_total = @not_admin_land_views.count 
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    # flash[:notice] = "Widget was successfully created."
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        # format.json { render :show, status: :created, location: @order }
      else
        format.html { redirect_to root_path, :flash => { :error => "Order wasn't created" } }
        # format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:email, :short_name, :phone, :city, :message)
  end

end

app/controllers/user_constraint.rb
class UserConstraint

  def matches?(request)
    request.env['warden'].authenticated? # are we authenticated?
    request.env['warden'].authenticate! # authenticate if not already
    # or even check any other condition such as request.env['warden'].user.is_admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/dashboard/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="active"><%= link_to 'Overview', dashboard_path %><span class="sr-only">(current)</span></a></li>
    <li><%= link_to 'Orders', '#orders_path' %></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="#">Reports</a></li>
    <li><a href="#">Analytics</a></li>
    <li><a href="#">Export</a></li>
  </ul>
 <!--  <ul class="nav nav-sidebar">
    <li><a href="">Nav item</a></li>
    <li><a href="">Nav item again</a></li>
    <li><a href="">One more nav</a></li>
    <li><a href="">Another nav item</a></li>
    <li><a href="">More navigation</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="">Nav item again</a></li>
    <li><a href="">One more nav</a></li>
    <li><a href="">Another nav item</a></li>
  </ul> -->
</div>

app/views/dashboard/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => "sidebar" %>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h1 class="page-header">Dashboard</h1>

      <div class="row placeholders">
        <!-- <div class="col-xs-6 col-sm-3 placeholder">
          <img src="/assets/200x200_sky.svg" class="img-responsive" alt="Generic placeholder thumbnail">
          <h4>Label</h4>
          <span class="text-muted">Something else</span>
        </div>
        <div class="col-xs-6 col-sm-3 placeholder">
          <img src="/assets/200x200_vine.svg" class="img-responsive" alt="Generic placeholder thumbnail">
          <h4>Label</h4>
          <span class="text-muted">Something else</span>
        </div> -->
        <div class="col-xs-12 col-sm-2 placeholder">
          <h2><%= @orders_today %></h2>
          <span class="text-muted">Orders Today</span>
          <h2><%= @land_views_today %></h2>
          <span class="text-muted">Landing Views Today</span>
          <h2><%= (@orders_today.to_f / @land_views_today).round(5) %></h2>
          <span class="text-muted">Conversion Today</span>
        </div>
        <div class="col-xs-12 col-sm-2 placeholder">
          <h2><%= @orders_total %></h2>
          <span class="text-muted">Orders Total</span>
          <h2><%= @land_views_total %></h2>
          <span class="text-muted">Landing Views Total</span>
          <h2><%= (@orders_total.to_f / @land_views_total).round(5) %></h2>
          <span class="text-muted">Conversion Total</span>
        </div>
        <div class="col-xs-12 col-sm-8 placeholder" style="margin-top: -20px;">
          <%= line_chart [ { name: 'Visits', data: @not_admin_land_views.group_by_day(:time, format: "%B %d, %Y").count}, { name: 'Orders', data: Order.group_by_day(:created_at, format: "%B %d, %Y").count} ], discrete: true %>
          <%#= line_chart Ahoy::Event.where(user_id:nil).group_by_day(&:time), discrete: true %>
        </div>
      </div>

      <%#= pie_chart Ahoy::Event.where(user_id:nil).group_by_day(:time, format: "%B %d, %Y").count %>

      <h2 class="sub-header">Orders</h2>
      <div class="table-responsive">
        <table id="orders_table" class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Email</th>
              <th>Short name</th>
              <th>City</th>
              <th>Phone</th>
              <th>Message</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
          <% Order.all.each do |ev| %>
            <tr>
              <td><%= ev.id %></td> 
              <td><%= ev.email %></td>
              <td style='min-width:100px'><%= ev.short_name %></td>
              <td><%= ev.city %></td>
              <td><%= ev.phone %></td>
              <td style='max-width:300px'><%= ev.message %></td>
              <td><%= ev.created_at.strftime("%A, %d %b %Y %H:%M %:z") %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <h2 class="sub-header">Events</h2>
      <div class="table-responsive">
        <table id="events_table" class="table table-striped">
          <thead>
            <tr>
              <!-- <th>#</th> -->
              <!-- <th>Visit ID</th> -->
              <!-- <th>User ID</th> -->
              <th>Name</th>
              <th>Properties</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
          <% @not_admin_events.each do |ev| %>
            <tr>
              <!-- <td><%#= ev.id %></td> --> 
              <!-- <td><%#= ev.visit_id %></td> -->
              <!-- <td><%#= ev.user %></td> -->
              <!-- <td><%#= ev.name %></td> -->
              <td><%= ev.properties['action'] %></td>
              <td><%= ev.properties['controller'] %></td>
              <td><%= ev.time.strftime("%A, %d %b %Y %H:%M %:z") %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready( function () {
    $('#orders_table').DataTable({
      "iDisplayLength": 10,
      "order": [[ 6, "desc" ]]
    });
    $('#events_table').DataTable({
      "iDisplayLength": 25,
      "order": [[ 2, "desc" ]]
    });
});
</script>

app/views/landing/index.html.erb
<%#= javascript_include_tag "/vendor/assets/javascripts/framework/bootstrap.min" %>
<%#= javascript_include_tag "bootstrap.min" %>
<%#= javascript_include_tag "bootstrap.min" %>
<%#= javascript_include_tag "formValidation.min.js", "/vendor/assets/javascripts" %>
<%#= stylesheet_link_tag    "formValidation.min.css" %>

<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-top: -50px;">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1><%= ab_test('headline_title', 'Example', 'Best') %> headline.</h1>
          <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Another example headline.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="data:image/gif;base64,R0lGODlhAQABAIAAAFVVVQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>One more for good measure.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">


  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4">
      <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" style="width: 140px; height: 140px;">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" style="width: 140px; height: 140px;">
      <h2>Heading</h2>
      <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" style="width: 140px; height: 140px;">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
      <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>
    <div class="col-md-5">
      <!-- <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image"> -->
      <img class="featurette-image img-responsive" src="/assets/500x500.svg" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-5">
      <img class="featurette-image img-responsive" src="/assets/500x500.svg" alt="Generic placeholder image">
    </div>
    <div class="col-md-7">
      <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
      <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
      <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-responsive" src="/assets/500x500.svg" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">

  <%= simple_form_for Order.new do |f| %>
    <div class="row">
      <div class="col-md-12 col-centered">
        <h2 class="featurette-heading" style="text-align:center; margin-top:0px; margin-bottom:40px;">Pre-Order <span class="text-muted">Review</span></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-1 col-md-6">
        <%= f.input :email %>
        <%= f.input :message, as: :text, input_html: { rows: '5', style: 'max-width:100%'}%>
      </div>
      <div class="col-md-3">
        <%= f.input :short_name %>
        <%= f.input :city %>
        <%= f.input :phone %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 col-centered">
        <%= f.button :submit %>
      </div>
    </div>
  <% end %>

  <hr class="featurette-divider"  style="margin-bottom:30px;">

  <!-- /END THE FEATURETTES -->
    <div class="row">
      <div class="col-md-3 col-centered">
        <p>
          <link class="social_share button_vk" data-type="vk"></link>
          <link class="social_share button_fb" data-type="fb"></link>
          <link class="social_share button_gg" data-type="gg"></link>
          <link class="social_share button_ok" data-type="ok"></link>
          <link class="social_share button_tw" data-type="tw"></link>
        </p>
      </div>
    </div>

  <hr class="featurette-divider" style="margin-top:30px;">

</div><!-- /.container -->

<script type="text/javascript">
$(document).ready(function() {
    $(document).on('click', '.social_share', function(){
        Share.go(this);
    });
    $('#new_order').formValidation({
        // locale: 'ru_RU',
        framework: 'bootstrap',
        message: 'This value is not valid',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            'order[email]': {
                validators: {
                    notEmpty: {
                        // message: 'The email address is required and can\'t be empty'
                    },
                    emailAddress: {
                        // message: 'The input is not a valid email address'
                    }
                }
            },
            'order[message]': {
                validators: {
                    notEmpty: {
                        // message: 'The message address is required and can\'t be empty'
                    },
                    stringLength: {
                        min: 6,
                        // message: 'The message must be more than 6 characters long'
                    }
                }
            },
            'order[short_name]': {
                message: 'The short_name is not valid',
                validators: {
                    notEmpty: {
                        message: 'The short_name is required and can\'t be empty'
                    },
                    stringLength: {
                        min: 6,
                        max: 30,
                        message: 'The short_name must be more than 6 and less than 30 characters long'
                    }
                }
            }
        }    
    });
});
</script>

app/views/layouts/_app_navbar.html.haml
.navbar-wrapper
  .container
    %nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Project name
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
            %li= link_to "Dashboard", dashboard_path
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Dropdown
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  %a{:href => "#"} Action
                %li
                  %a{:href => "#"} Another action
                %li
                  %a{:href => "#"} Something else here
                %li.divider
                %li.dropdown-header Nav header
                %li
                  %a{:href => "#"} Separated link
                %li
                  %a{:href => "#"} One more separated link

app/views/layouts/_dash_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Project name', root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'A/B Testing', split_path
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.short_name
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path, :class => "", :id => "login"
      %form.navbar-form.navbar-right
        %input.form-control{:placeholder => "Search...", :type => "text"}/

app/views/layouts/_footer.html.haml
.container
  %footer
    %p.pull-right
      %a{:href => "#"} Back to top
    %p
      \&copy; 2014 Company, Inc. &middot;
      %a{:href => "#"} Privacy
      \&middot;
      %a{:href => "#"} Terms

app/views/layouts/_html_head.html.haml
%head
  / %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %meta{:charset => "utf-8"}/
  %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
  %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %meta{:content => "", :name => "description"}/
  %meta{:content => "", :name => "author"}/
  %title Landing Page
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  %head
    / %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title CarRevizor
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |key, value|
      %div{:class => flash_class(key), :id => "flasher"}
        = value

    = yield

app/views/layouts/dashboard.html.haml
!!!
%html  
  = render :partial => "layouts/html_head"
  %body
    - flash.each do |key, value|
      %div{:class => flash_class(key), :id => "flasher"}
        = value
    = render :partial => "layouts/dash_navbar"
    = yield